### ISSUE TITLE
PeerGUI not Mac compatible

### ISSUE THREAD

**Issue by pferdy** [Convex-Dev/design#23]
Copy and Paste into PeerGui does not work, either with keyboard or right click.

**Comment by mikera** [comment]
Thanks, please:
a) Re-open the issue here: https://github.com/Convex-Dev/convex/issues (since PeerGUI is part of main repository)
b) Clarify what you are doing and you expect to see (especially w.r.t. keyboard keys used).

**Comment by mikera** [comment]
Closing as this should be moved to the correct repository
