### ISSUE TITLE
whitepaper typos (1/14)

### ISSUE THREAD

**Issue by wildyelir** [Convex-Dev/design#26]
**Pg 8 (Pagr. 2 of Consensus Algorithm)** 

Typo:

In contract to blockchains however, the blocks are not linked to previous blocks - there is no “chain” as such.

Corrected:

In **contrast** to blockchains however, the blocks are not linked to previous blocks - there is no “chain” as such.

**Comment by wildyelir** [comment]
Typo:

A Peer proposed a Block for consensus simply by appending it to its current Ordering, where this Ordering includes all Blocks up to the Consensus Point, plus any additional Blocks still to be confirmed in consensus.

Corrected:

A Peer **proposes** a Block for consensus simply by appending it to its current Ordering, where this Ordering includes all Blocks up to the Consensus Point, plus any additional Blocks still to be confirmed in consensus.

**Comment by wildyelir** [comment]
Pg 17 (First Pagr. of Convergent Consensus)

Typo:

Convex uses a variant of **Convergent Replicated Data Types (CRDTs**) ensure that the Network converges to Consensus.

Corrected:

Convex uses a variant of **Conflict-free Replicated Data Types (CRDTs**) ensure that the Network converges to Consensus.

**Comment by wildyelir** [comment]
Pg 18 (2nd Pagr. of Stake-weighted voting) - missing comma causes confusion around 'conflict between Orderings..'

Typo:

At each Belief Merge step, if there is a conflict between Orderings the Peer computes the total share of stake voting for each proposed Block in the next position after the current Consensus Point. It is able to do this because it has a view of the Orderings proposed by all other Peers.

Corrected:

At each Belief Merge step, if there is a conflict between Orderings**,** the Peer computes the total share of stake voting for each proposed Block in the next position after the current Consensus Point. It is able to do this because it has a view of the Orderings proposed by all other Peers.

**Comment by wildyelir** [comment]
Pg 21 (2nd Parg. of Illustrations)

Typo:

We can visualise this initial situation as a Matrix, where each row is the Belief **help** by one peer, and each column represents the latest signed Ordering observed by each peer from another peer. Each Peer also has knowledge of the current Consensus defined by o, which is also its Proposed Consensus.

Corrected:

We can visualise this initial situation as a Matrix, where each row is the Belief **held** by one peer, and each column represents the latest signed Ordering observed by each peer from another peer. Each Peer also has knowledge of the current Consensus defined by o, which is also its Proposed Consensus.

**Comment by wildyelir** [comment]
Pg 34 (2nd Parg. of Time)

Typo:

The juice price a dynamically varying price that adjusts with amount of execution performed per unit time by the Convex network as a whole:

Corrected:

The juice price **is** a dynamically varying price that adjusts with amount of execution performed per unit time by the Convex network as a whole:

**Comment by wildyelir** [comment]
Pg 36 (Transparent persistence)

Is this supposed to be JVM or EVM ?
![Screenshot 2024-01-14 220108](https://github.com/Convex-Dev/design/assets/124108538/96678a36-5101-4530-977a-87ed5a62c97b)

**Comment by wildyelir** [comment]
Pg 48 (2nd sentence of Actor considerations)

Typo:

However, in most cases Actors have no need for a Memory Allowance because **and** memory consumption will be accounted for against a User account that was the Origin of a transaction.

Corrected:

However, in most cases Actors have no need for a Memory Allowance because memory consumption will be accounted for against a User account that was the Origin of a transaction.

**Comment by mikera** [comment]
Thanks @wildyelir I will run through and check these.  

For the future, feel free to send a PR for small edits!

**Comment by wildyelir** [comment]
Will do.

**Comment by mikera** [comment]
Re-checked all these and made sure they are represented in the latest version.
