### ISSUE TITLE
Destructuring with "non-terminal" &

### ISSUE THREAD

**Issue by helins** [Convex-Dev/design#4]
Following convex-dev/convex#62, this issue aims to discuss using `&` in destructuring like this:

```clojure
(let [[a & b c d e] [1 2 3 4 5 6 7 8]] [a b c d e])

;; => [1 [2 3 4 5] 6 7 8]
```

Although I can guess some rationale behind it, it would be helpful if some concrete use cases can be pointed. It seems the point is being able to reliably destructure from the end as well but personally, I never needed a feature like that in Clojure.

I have no firm opinion about it besides the fact that it looks expert-friendly, hence error-prone for less experienced users.

**Comment by mikera** [comment]
This is now covered in CAD026
