### ISSUE TITLE
CNS authority

### ISSUE THREAD

**Issue by helins** [Convex-Dev/design#5]
Current implementation of CNS allows anyone to register any name. In other words, there is no authority preventing abuse. For instance, if the Foundation releases a library called `convex.market`, an attacker can just as easily release a malicious copycat `convex.rnarket` (**RN** instead of **M**). Or release an entirely different but malicious library that looks like it has been issued by the Foundation.

On the other hand, allowing any one to register a library at will is a feature. One way to have both is to rely on namespacing, where unnamespaced names can be register at will but namespaced ones must go through a validation process. I guess the Foundation could act as the authority since it is meant to apply some form of lightweight governance whenever needed. This still assumes that there is absolutely no confusion between something like `convex/market` and `convex.market`, which remains tricky.

**Comment by mikera** [comment]
Since added as CAD14
